### ISSUE TITLE
Allow to customize the window title

### ISSUE THREAD

**Issue by sschuberth** [Wavesonics/compose-multiplatform-file-picker#7]
It would be nice if the window's title could be customized (e.g. from "Open File" on Linux / KDE) to any custom text (like "Open Image").

**Comment by StefanOltmann** [comment]
It would even be better to have a empty string instead of "Choose directory", because this is not localized right now.

See this case where we got the German file picker:

<img width="782" src="https://github.com/Wavesonics/compose-multiplatform-file-picker/assets/9299303/8a33434a-5c9f-4f3d-a9b4-bcbf8e05477d">

**Comment by StefanOltmann** [comment]
@shalva97 What do you think about this issue?

**Comment by shalva97** [comment]
The first idea that comes to my mind is to just remove the hardcoded string. Maybe after all people just don't need to change title anyway.

Or I could add a parameter with default value....

**Comment by shalva97** [comment]
okay a bit of work is here https://github.com/Wavesonics/compose-multiplatform-file-picker/pull/96

**Comment by StefanOltmann** [comment]
Great 🙂

**Comment by StefanOltmann** [comment]
@sschuberth You can close the issue now. 🙂

**Comment by sschuberth** [comment]
> okay a bit of work is here #96

Great that this was merged 👍🏻
